# dbt_assets.py — Wraps every dbt model as a Dagster software-defined asset
#
# WHAT THIS DOES: Instead of running `dbt run` manually, Dagster manages it.
# The @dbt_assets decorator reads manifest.json (the compiled dbt dependency graph)
# and automatically creates one Dagster asset per dbt model.
#
# After this file is imported, the Dagster UI will show 11 assets:
#   stg_analyses, stg_coverage, stg_portfolio, stg_subscriptions
#   int_pipeline_health, int_user_activity
#   mart_coverage, mart_quality, mart_usage
#   (plus any seeds or snapshots if you add them later)
#
# PREREQUISITE: You must compile the dbt project FIRST to generate manifest.json:
#   cd apps/plotlot/dbt/plotlot_dbt && dbt compile
# Without manifest.json, @dbt_assets cannot discover the models and will error.

from pathlib import Path
# pathlib.Path provides OS-agnostic file path manipulation
# Path(__file__) = absolute path to this Python file
# .parent.parent... navigates up the directory tree

from dagster_dbt import DbtCliResource, dbt_assets
# DbtCliResource: tells Dagster where the dbt project is and how to run dbt CLI commands
# dbt_assets: decorator that reads manifest.json and creates one Dagster asset per dbt model
# Both come from the dagster-dbt package (installed in pyproject.toml)


# ─────────────────────────────────────────────────────────────────────────────
# Compute the absolute path to the dbt project directory
# ─────────────────────────────────────────────────────────────────────────────
# __file__ = .../apps/plotlot/dagster/dagster_project/assets/dbt_assets.py
# .parent   = ...dagster_project/assets/
# .parent   = ...dagster_project/
# .parent   = ...dagster/
# .parent   = ...apps/plotlot/
# / "dbt" / "plotlot_dbt" = ...apps/plotlot/dbt/plotlot_dbt/
DBT_PROJECT_DIR = Path(__file__).parent.parent.parent.parent / "dbt" / "plotlot_dbt"
# This path construction is portable — works on any machine regardless of where the repo is cloned


# ─────────────────────────────────────────────────────────────────────────────
# DbtCliResource — tells Dagster where the dbt project lives
# ─────────────────────────────────────────────────────────────────────────────
dbt_resource = DbtCliResource(
    project_dir=str(DBT_PROJECT_DIR),
    # Absolute path to the dbt project (where dbt_project.yml lives)
    # Dagster uses this to call `dbt run`, `dbt test`, `dbt compile` etc.
    # str() converts the Path object to a string (DbtCliResource expects str, not Path)
)


# ─────────────────────────────────────────────────────────────────────────────
# @dbt_assets — the main decorator that creates all dbt model assets
# ─────────────────────────────────────────────────────────────────────────────
@dbt_assets(
    manifest=DBT_PROJECT_DIR / "target" / "manifest.json",
    # manifest.json is generated by `dbt compile` or `dbt run`
    # It contains the full dependency graph: which models exist, what they select from,
    # and in what order they must run (resolved from {{ ref() }} and {{ source() }} calls)
    # Dagster reads this JSON to:
    #   1. Create one asset per model node in the graph
    #   2. Set up asset dependencies (stg_* before int_*, int_* before mart_*)
    #   3. Know which dbt models correspond to which database tables/views
)
def plotlot_dbt_assets(context, dbt: DbtCliResource):
    # context: AssetExecutionContext — provides logging, metadata attachment, run info
    # dbt: DbtCliResource — injected by Dagster (matches the resource declared in Definitions)
    #      wait — DbtCliResource is NOT declared in Definitions above
    #      In dagster-dbt, dbt is passed via the function parameter, not resources dict
    #      The @dbt_assets decorator handles this injection automatically

    yield from dbt.cli(["run"], context=context).stream()
    # dbt.cli(["run"]) = equivalent to running `dbt run` on the command line
    # This executes all models in the dbt project (in dependency order from manifest.json)
    # .stream() converts the dbt CLI output to a stream of Dagster events
    # yield from: the generator pattern — each dbt model completion emits a Dagster event
    # Dagster UI shows each model as it completes (not just "dbt done" at the end)

    yield from dbt.cli(["test"], context=context).stream()
    # dbt.cli(["test"]) = equivalent to running `dbt test` on the command line
    # Runs all tests declared in schema.yml (unique, not_null, accepted_values)
    # If a test fails, Dagster marks the asset as FAILED with the failing SQL
    # yield from: again streaming — you see test results in real-time in the Dagster UI
