"""Docx renderer — assembles rendered clauses into a .docx file.

Uses python-docx to build a professional Word document from the
ordered list of RenderedClause objects.
"""

from __future__ import annotations

import io
import logging
from datetime import datetime, timezone
from typing import Any

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH

from plotlot.clauses.schema import (
    AssemblyConfig,
    ClauseFormatting,
    DealContext,
    DocumentType,
    GeneratedDocument,
    RenderedClause,
)

logger = logging.getLogger(__name__)

# Document type → title mapping
_DOC_TITLES: dict[DocumentType, str] = {
    DocumentType.loi: "Letter of Intent",
    DocumentType.psa: "Purchase Contract and Escrow Instructions",
    DocumentType.deal_summary: "Deal Summary Report",
    DocumentType.addendum: "Addendum",
    DocumentType.acknowledgements: "Seller Acknowledgements",
    DocumentType.promissory_note: "Promissory Note",
    DocumentType.deed_of_trust: "Deed of Trust",
}


def render_docx(
    clauses: list[RenderedClause],
    config: AssemblyConfig,
    context: DealContext,
) -> GeneratedDocument:
    """Render an ordered list of clauses into a .docx file.

    Args:
        clauses: Ordered, rendered clauses from the assembly engine.
        config: Assembly configuration (document type, branding, etc.).
        context: Deal context for metadata (address, dates).

    Returns:
        GeneratedDocument with .docx bytes.
    """
    doc = Document()

    # Title
    title_text = _DOC_TITLES.get(config.document_type, config.document_type.value.upper())
    title = doc.add_heading(title_text, level=1)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Date
    now = datetime.now(timezone.utc)
    doc.add_paragraph(f"Date: {context.effective_date or now.strftime('%B %d, %Y')}")
    doc.add_paragraph("")

    # Render each clause
    for clause in clauses:
        _render_clause_to_doc(doc, clause)

    # Footer with PlotLot branding
    if config.include_plotlot_branding:
        doc.add_paragraph("")
        p = doc.add_paragraph()
        p.add_run("Generated by PlotLot — ").italic = True
        p.add_run(context.generated_at or now.strftime("%Y-%m-%d %H:%M UTC")).italic = True

    # Save to bytes
    buf = io.BytesIO()
    doc.save(buf)

    # Build filename
    address_part = (
        (context.property_address or context.formatted_address or "property")
        .split(",")[0]
        .replace(" ", "_")[:30]
    )
    doc_type_prefix = config.document_type.value.upper()
    filename = f"{doc_type_prefix}_{address_part}_{now.strftime('%Y%m%d')}.docx"

    return GeneratedDocument(
        filename=filename,
        content_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        data=buf.getvalue(),
    )


def _render_clause_to_doc(doc: Any, clause: RenderedClause) -> None:  # type: ignore[valid-type]
    """Add a single rendered clause to the document.

    Handles different formatting styles: normal paragraphs, tables,
    checklists, and numbered lists.
    """
    fmt = clause.formatting or ClauseFormatting()

    # Page break if requested
    if fmt.page_break_before:
        doc.add_page_break()

    # Heading
    if clause.title:
        doc.add_heading(clause.title, level=min(fmt.heading_level, 4))

    content = clause.rendered_content.strip()
    if not content:
        return

    # Render based on style
    if fmt.style == "table" and fmt.columns:
        _render_table(doc, content, fmt.columns)
    elif fmt.style == "checklist":
        _render_checklist(doc, content)
    elif fmt.style == "numbered_list":
        _render_numbered_list(doc, content)
    else:
        _render_paragraphs(doc, content)


def _render_paragraphs(doc: Any, content: str) -> None:  # type: ignore[valid-type]
    """Render content as plain paragraphs (split by double newlines)."""
    for block in content.split("\n\n"):
        text = block.strip()
        if text:
            doc.add_paragraph(text)


def _render_table(doc: Any, content: str, columns: list[str]) -> None:  # type: ignore[valid-type]
    """Render content as a table.

    Content should have lines formatted as: label | value
    """
    lines = [line.strip() for line in content.split("\n") if line.strip()]
    if not lines:
        return

    num_cols = len(columns)
    table = doc.add_table(rows=len(lines) + 1, cols=num_cols)
    table.style = "Table Grid"

    # Header row
    for i, col_name in enumerate(columns):
        table.rows[0].cells[i].text = col_name

    # Data rows
    for row_idx, line in enumerate(lines):
        parts = [p.strip() for p in line.split("|")]
        for col_idx in range(min(len(parts), num_cols)):
            table.rows[row_idx + 1].cells[col_idx].text = parts[col_idx]


def _render_checklist(doc: Any, content: str) -> None:  # type: ignore[valid-type]
    """Render content as a checklist (each line as a bullet)."""
    for line in content.split("\n"):
        text = line.strip()
        if text:
            doc.add_paragraph(text, style="List Bullet")


def _render_numbered_list(doc: Any, content: str) -> None:  # type: ignore[valid-type]
    """Render content as a numbered list."""
    for line in content.split("\n"):
        text = line.strip()
        if text:
            doc.add_paragraph(text, style="List Number")
